POST http://localhost:3000/api/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzEyOGEyNThkMGE1YzFkMjdkYjc0ZmIiLCJpYXQiOjE2NjM4MDIyODR9.gsCvGiqL3-ueBWNzRbHAaicaUUO_kMm6UmZtQhXI-DI

{
  "name": "Nova task",
  "previsionDate": "2022-09-15"
}